### ISSUE TITLE
Redirect after success

### ISSUE THREAD

**Issue by jimthedev** [scriptify/mrnote#1]
Currently you're never redirected after the board is created. I was able to tell by looking in dev tools Network tab to see that it was created properly, but you wouldn't know it if you didn't know how to do this.

**Comment by scriptify** [comment]
I now replaced the 'success' icon with a redirect icon. When the user clicks on this icon, he will be redirected to the noteboard (write access).
This feature was already available before, but the success icon wasn't clear enough.
Thanks for pointing that out!
